news/urls.py
from django.urls import path
from . import views
from .views import listaPostView,listaGiornalistiView,listaArticoliGiornalistaView

app_name = 'news'
urlpatterns = [
    path('lista-articoli', listaPostView.as_view(), name='lista_articoli'),
    path('lista-giornalisti',listaGiornalistiView.as_view(), name='lista_giornalisti'),
    path('lista-articoli-giornalista/<int:pk>', listaArticoliGiornalistaView, name='lista_articoli_giornalista'),
]

verificaFattoretti/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='Home Page'),
    path('news/',include('news.urls',namespace='news')),

]

news/models.py
from django.db import models

# Create your models here.
class NewsGiornalistiModel(models.Model):
    nome = models.CharField(max_length=100)
    def __str__(self):
        return self.nome

class NewsArticoliModel(models.Model):
    titolo = models.CharField(max_length=100)
    contenuto = models.TextField()
    autore = models.ForeignKey(NewsGiornalistiModel, on_delete=models.CASCADE, related_name="articoli",default=1,)

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

news/forms.py
from django import forms
from .models import NewsArticoliModel,NewsGiornalistiModel


class NewsArticoliModelForm(forms.ModelForm):

    class Meta:
        model = NewsArticoliModel
        fields = "__all__"

class NewsGiornalistiModelForm(forms.ModelForm):

    class Meta:
        model = NewsGiornalistiModel
        fields = "__all__"

news/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import NewsArticoliModel,NewsGiornalistiModel
from django.shortcuts import get_object_or_404

# Create your views here.
class listaPostView(ListView):
    model = NewsArticoliModel #modello dei dati da utilizzare 
    template_name = "news/lista_articoli.html"  #pagina per mostrare i dati

class listaGiornalistiView(ListView):
    model = NewsGiornalistiModel #modello dei dati da utilizzare 
    template_name = "news/lista_giornalisti.html"  #pagina per mostrare i dati

def listaArticoliGiornalistaView(request,pk):
    giornalista=get_object_or_404(NewsGiornalistiModel, id=pk)
    articoli=giornalista.articoli.all()
    context = {'giornalista': giornalista,
               'newsarticolimodel_list': articoli,
               }
    return render(request, 'news/lista_articoli.html', context)

verificaFattoretti/views.py
from django.shortcuts import render,HttpResponse
import datetime

def index(request): 
    return render(request, "home.html")

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{%block titolo%}News{%endblock titolo%}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
      <a class="navbar-brand" href="/">Web apps</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/"> <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              News
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">Articoli</a>
              <a class="dropdown-item" href="{% url 'news:lista_giornalisti' %}">Giornalisti</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    
    <div class="container">
        {%block contenuti%}

        {%endblock contenuti%}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html'%}

{%block contenuti%}
	
<div class="row">
    <div class="col-8">
        <div class="card my-2">
            <div class="card-header">
              <h3>VERIFICA DJANGO</h3>
            </div>
            <div class="card-body">
              <h3>Fattoretti Samuele</h3>
            </div>
            <div class="card-footer">
              <b>Eseguita il 20/05/2020 </b> 
            </div>
        </div>
    </div>
  </div>
    
{%endblock contenuti%}

templates/news/lista_articoli.html
{% extends 'base.html' %}
{% block contenuti %}
    {% if giornalista %}
        <h5  class="my-3" >Elenco degli articoli di {{ giornalista.nome }}:</h5>
    {% else %}
        <h5  class="my-3" >Elenco di tutti gli articoli:</a></h5>
    {% endif %}

    {% for articolo in newsarticolimodel_list %}
        <p>{{forloop.counter}}){{ articolo.titolo }}</a><br>
        {{ articoli.contenuto }}
        <small>({{ articolo.autore }})</a></small> </p>
    {% endfor %}
{% endblock contenuti %}

templates/news/lista_giornalisti.html
{% extends 'base.html' %}
{% block contenuti %}
    {% for post in newsgiornalistimodel_list %}
        <p>{{forloop.counter}})
            <a href="{% url 'news:lista_articoli_giornalista' pk=post.id %}">{{ post.nome }}</a></p>
    {% endfor %}
{% endblock contenuti %}